### PR TITLE
unlet error in syntax/php.vim file

### PR DESCRIPTION
**Pull request by exu**
closing https://github.com/spf13/PIV/issues/10

### CODE REVIEW

**Comment by greduan** [comment]
Really interested in this, since I also get an error regarding PHP syntax files.

Any updates on this @exu and @spf13.

**Comment by exu** [comment]
Hi it looks that this project is dead. I'm Now emacs user :)
19-12-2012 01:17, "Eduan Lavaque" notifications@github.com napisał(a):

**Comment by greduan** [comment]
@exu I see. Hope that's not for long. :)
Hope you enjoy your Emacs life. ;)

**Comment by spf13** [comment]
Sorry for having this sit for so long. I didn't notice this pull request until the comment today. Merging in now.

**Comment by greduan** [comment]
Yay! Glad I commented. :P

**Pull request merged**
